import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Image, ActivityIndicator, TextInput } from 'react-native';
import { useRouter } from 'expo-router';
import { ArrowLeft, Sparkles, Shield, Compass, FileText, CheckCircle, Activity, Info, Calendar, User as UserIcon } from 'lucide-react-native';
import { ASBColors, ASBFonts } from '../../theme/tokens';
import { GlassCard } from '../../components/common/GlassCard';
import { GradientButton } from '../../components/common/GradientButton';
import { useAuth } from '../../context/AuthContext';
import { API_ENDPOINTS } from '../../api/config';
import { formatDobForApi } from '../../api/client';
import { calculateNumerologyProfile } from '../../utils/numerologyMath';

import { getGuestProfile, saveGuestProfile } from '../../utils/guestStorage';

export default function MysticalTriangleScreen() {
  const router = useRouter();
  const { user } = useAuth();

  const [nameInput, setNameInput] = useState(user?.name || '');
  const [dobInput, setDobInput] = useState(user?.dob || '');
  const [activeName, setActiveName] = useState(user?.name || '');
  const [activeDob, setActiveDob] = useState(user?.dob || '');

  React.useEffect(() => {
    if (user?.name) {
      setNameInput(user.name);
      setActiveName(user.name);
    }
    if (user?.dob) {
      setDobInput(user.dob);
      setActiveDob(user.dob);
    }
    getGuestProfile().then((g) => {
      if (g.name) {
        setNameInput((prev) => prev || g.name);
        setActiveName((prev) => prev || g.name);
      }
      if (g.dob) {
        setDobInput((prev) => prev || g.dob);
        setActiveDob((prev) => prev || g.dob);
      }
    });
  }, [user]);

  const [imageLoading, setImageLoading] = useState(true);
  const [imageError, setImageError] = useState(false);

  const formatDobInput = (text: string) => {
    const cleaned = text.replace(/\D/g, '');
    let formatted = cleaned;
    if (cleaned.length > 2 && cleaned.length <= 4) {
      formatted = `${cleaned.slice(0, 2)}-${cleaned.slice(2)}`;
    } else if (cleaned.length > 4) {
      formatted = `${cleaned.slice(0, 2)}-${cleaned.slice(2, 4)}-${cleaned.slice(4, 8)}`;
    }
    return formatted;
  };

  const handleGenerate = () => {
    if (!nameInput.trim()) {
      return;
    }
    if (!dobInput.trim()) {
      return;
    }
    saveGuestProfile(nameInput.trim(), dobInput.trim());
    setActiveName(nameInput.trim());
    setActiveDob(dobInput.trim());
    setImageLoading(true);
    setImageError(false);
  };

  const effectiveName = activeName || 'Seeker';
  const profile = activeDob ? calculateNumerologyProfile(activeDob, effectiveName) : null;
  const formattedDob = activeDob ? formatDobForApi(activeDob) : '';

  // Real backend Mystical Triangle PNG image URL generated by Python FastAPI engine
  const backendImageUrl = activeDob
    ? `${API_ENDPOINTS.REPORT_BASE}/api/numerology/mystical-triangle.png?dob=${encodeURIComponent(formattedDob)}&name=${encodeURIComponent(effectiveName)}`
    : '';

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      {/* Header Bar */}
      <View style={styles.navRow}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <ArrowLeft size={20} color={ASBColors.darkNavy} />
        </TouchableOpacity>
        <Text style={styles.navTitle}>Mystical Triangle Report</Text>
      </View>

      <Text style={styles.subtitle}>Sacred Chaldean Triangle Geometry & Compound Vibration Nodes</Text>

      {/* Input Details Form Card (Allows Guest & Logged-In Users to calculate for any DOB) */}
      <GlassCard style={styles.inputFormCard}>
        <View style={styles.formTitleRow}>
          <Sparkles size={16} color={ASBColors.primaryPurple} />
          <Text style={styles.formTitle}>ENTER BIRTH DETAILS TO CALCULATE REPORT</Text>
        </View>

        <View style={styles.inputRow}>
          <View style={{ flex: 1 }}>
            <Text style={styles.inputLabel}>FULL NAME *</Text>
            <TextInput
              style={styles.textInput}
              placeholder="e.g. Bhaskar Sharma"
              value={nameInput}
              onChangeText={setNameInput}
              placeholderTextColor={ASBColors.textMuted}
            />
          </View>

          <View style={{ flex: 1 }}>
            <Text style={styles.inputLabel}>DATE OF BIRTH (DD-MM-YYYY) *</Text>
            <TextInput
              style={styles.textInput}
              placeholder="e.g. 11-04-2004"
              value={dobInput}
              onChangeText={(t) => setDobInput(formatDobInput(t))}
              placeholderTextColor={ASBColors.textMuted}
              keyboardType="number-pad"
              maxLength={10}
            />
          </View>
        </View>

        <GradientButton
          title="Calculate Mystical Triangle"
          variant="primary"
          icon={<Compass size={18} color="#FFF" />}
          onPress={handleGenerate}
          style={{ marginTop: 10 }}
        />
      </GlassCard>

      {!activeDob ? (
        <GlassCard style={[styles.imageCard, { paddingVertical: 32 }]}>
          <Calendar size={36} color={ASBColors.primaryPurple} />
          <Text style={{ fontSize: 14, fontWeight: '700', color: ASBColors.darkNavy, marginTop: 12, textAlign: 'center' }}>
            Enter your Name and Date of Birth above to generate your sacred Mystical Triangle diagram!
          </Text>
        </GlassCard>
      ) : (
        <>
          {/* Real Backend Generated Mystical Triangle Image Card */}
          <GlassCard style={styles.imageCard}>
            <View style={styles.cardTagRow}>
              <Sparkles size={14} color={ASBColors.primaryPurple} />
              <Text style={styles.cardTagText}>REAL BACKEND GEOMETRY DIAGRAM FOR {effectiveName.toUpperCase()} ({activeDob})</Text>
            </View>

            <View style={styles.imgWrapper}>
              {imageLoading && (
                <View style={styles.loadingBox}>
                  <ActivityIndicator size="large" color={ASBColors.primaryPurple} />
                  <Text style={styles.loadingText}>Rendering Sacred Chaldean Triangle for {activeDob}...</Text>
                </View>
              )}

              {!imageError ? (
                <Image
                  source={{ uri: backendImageUrl }}
                  style={styles.triangleImg}
                  onLoadStart={() => setImageLoading(true)}
                  onLoadEnd={() => setImageLoading(false)}
                  onError={() => {
                    setImageLoading(false);
                    setImageError(true);
                  }}
                  resizeMode="contain"
                />
              ) : (
                <View style={styles.fallbackTriangle}>
                  <View style={styles.triangleShape}>
                    <Text style={styles.triangleApex}>Soul #{profile?.moolank}</Text>
                    <View style={styles.triangleMidRow}>
                      <Text style={styles.triangleNode}>Life Path #{profile?.bhagyank}</Text>
                      <Text style={styles.triangleNode}>Expr #{profile?.expression}</Text>
                    </View>
                  </View>
                </View>
              )}
            </View>
          </GlassCard>

          {/* Core Vibrational Triad */}
          <Text style={styles.sectionHeading}>SACRED NUMERICAL APEXES</Text>
          <View style={styles.gridRow}>
            <GlassCard style={styles.apexCard}>
              <Text style={styles.apexLabel}>ROOT SOUL (G)</Text>
              <Text style={styles.apexValue}>{profile?.moolank}</Text>
              <Text style={styles.apexDesc}>Subconscious spiritual baseline & inner drive.</Text>
            </GlassCard>

            <GlassCard style={styles.apexCard}>
              <Text style={styles.apexLabel}>LIFE PATH (E)</Text>
              <Text style={styles.apexValue}>{profile?.bhagyank}</Text>
              <Text style={styles.apexDesc}>Daily destiny trajectory & primary lessons.</Text>
            </GlassCard>

            <GlassCard style={styles.apexCard}>
              <Text style={styles.apexLabel}>EXPRESSION (F)</Text>
              <Text style={styles.apexValue}>{profile?.expression}</Text>
              <Text style={styles.apexDesc}>Outer manifestation & talent projection.</Text>
            </GlassCard>
          </View>

          {/* Chaldean Karmic Destiny Lines Analysis */}
          <GlassCard style={styles.analysisCard}>
            <View style={styles.analysisHeaderRow}>
              <Activity size={18} color={ASBColors.primaryPurple} />
              <Text style={styles.analysisTitle}>CHALDEAN KARMIC DESTINY LINES</Text>
            </View>

            <View style={styles.nodeItem}>
              <CheckCircle size={16} color={ASBColors.goodGreen} />
              <View style={{ flex: 1 }}>
                <Text style={styles.nodeTitle}>Primary Karmic Node ({profile?.moolank} - {profile?.bhagyank})</Text>
                <Text style={styles.nodeDesc}>
                  Your birth numbers form a harmonious sub-plane frequency balancing leadership with spiritual growth.
                </Text>
              </View>
            </View>

            <View style={styles.nodeItem}>
              <CheckCircle size={16} color={ASBColors.goodGreen} />
              <View style={{ flex: 1 }}>
                <Text style={styles.nodeTitle}>Destiny Peak Cycle (Personal Year #{profile?.personalYear})</Text>
                <Text style={styles.nodeDesc}>
                  Year #{profile?.personalYear} activates key decision windows in financial growth and spiritual alignment.
                </Text>
              </View>
            </View>
          </GlassCard>

          {/* CTA Button to Full Master PDF */}
          <GradientButton
            title="Download Master 100-Page Dossier"
            variant="primary"
            icon={<FileText size={18} color="#FFF" />}
            onPress={() => router.push('/reports/pdf-viewer')}
            style={{ marginTop: 12 }}
          />
        </>
      )}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: ASBColors.bgWarmIvory,
  },
  content: {
    padding: 16,
    paddingTop: 54,
    paddingBottom: 40,
    gap: 14,
    width: '100%',
    maxWidth: 800,
    alignSelf: 'center',
  },
  navRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: ASBColors.borderIvory,
  },
  navTitle: {
    fontSize: 18,
    fontFamily: ASBFonts.heading,
    color: ASBColors.darkNavy,
  },
  subtitle: {
    fontSize: 12,
    color: ASBColors.textMuted,
    marginTop: -4,
    marginBottom: 8,
  },
  imageCard: {
    padding: 16,
    alignItems: 'center',
  },
  cardTagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
  },
  cardTagText: {
    fontSize: 10,
    fontFamily: ASBFonts.bodyBold,
    color: ASBColors.primaryPurple,
    letterSpacing: 1,
  },
  imgWrapper: {
    width: '100%',
    height: 260,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: ASBColors.borderPurple,
  },
  triangleImg: {
    width: '100%',
    height: '100%',
  },
  loadingBox: {
    position: 'absolute',
    alignItems: 'center',
    gap: 8,
    zIndex: 10,
  },
  loadingText: {
    fontSize: 12,
    color: ASBColors.textMuted,
  },
  fallbackTriangle: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  triangleShape: {
    alignItems: 'center',
    gap: 20,
  },
  triangleApex: {
    fontSize: 18,
    fontFamily: ASBFonts.heading,
    color: ASBColors.primaryPurple,
  },
  triangleMidRow: {
    flexDirection: 'row',
    gap: 30,
  },
  triangleNode: {
    fontSize: 14,
    fontFamily: ASBFonts.bodyBold,
    color: ASBColors.darkNavy,
  },
  sectionHeading: {
    fontSize: 12,
    fontFamily: ASBFonts.heading,
    color: ASBColors.darkNavy,
    letterSpacing: 1.5,
    marginTop: 8,
  },
  gridRow: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  apexCard: {
    flex: 1,
    padding: 12,
    alignItems: 'center',
  },
  apexLabel: {
    fontSize: 9,
    fontFamily: ASBFonts.bodyBold,
    color: ASBColors.primaryPurple,
    letterSpacing: 0.5,
  },
  apexValue: {
    fontSize: 24,
    fontFamily: ASBFonts.heading,
    color: ASBColors.darkNavy,
    marginVertical: 4,
  },
  apexDesc: {
    fontSize: 10,
    color: ASBColors.textMuted,
    textAlign: 'center',
  },
  analysisCard: {
    padding: 16,
    gap: 12,
  },
  analysisHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  analysisTitle: {
    fontSize: 12,
    fontFamily: ASBFonts.heading,
    color: ASBColors.darkNavy,
    letterSpacing: 1,
  },
  nodeItem: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
  },
  nodeTitle: {
    fontSize: 12,
    fontFamily: ASBFonts.bodyBold,
    color: ASBColors.darkNavy,
  },
  nodeDesc: {
    fontSize: 11,
    color: ASBColors.textMuted,
    marginTop: 2,
    lineHeight: 16,
  },
  inputFormCard: {
    padding: 16,
    marginBottom: 8,
  },
  formTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  formTitle: {
    fontSize: 11,
    fontFamily: ASBFonts.heading,
    color: ASBColors.primaryPurple,
    letterSpacing: 1,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 8,
  },
  inputLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: ASBColors.darkNavy,
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  textInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: ASBColors.borderPurple,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 13,
    color: ASBColors.darkNavy,
  },
});
